### ISSUE TITLE
BLE_DEVICE_ID - Not Declared

### ISSUE THREAD

**Issue by dookie454** [renatobo/DucatiPanigaleCanBus#3]
Hey Renato, I am getting a "BLE_DEVICE_ID" not declared error with stock code.

I searched for it, and found some lower case, so changed those to upper case, and it solved the problem.   Should that be a problem?  Maybe only a problem with Arduino IDE?

Examples:
char BLE_DEVICE_ID[12];   // was  char ble_device_id[12]; 

sprintf(BLE_DEVICE_ID, "%s-%04X", BLE_DEVICE_ID_PREFIX, chip);  // was sprintf(ble_device_id, "%s-%04X", BLE_DEVICE_ID_PREFIX, chip);   

NimBLEDevice::init(BLE_DEVICE_ID);  //  was  NimBLEDevice::init(ble_device_id);

**Comment by renatobo** [comment]
There is a `BLE_DEVICE_ID_PREFIX` , but no `BLE_DEVICE_ID`: it was removed in commit [refactor(device name): Changed device name to include chip id](https://github.com/renatobo/DucatiPanigaleCanBus/commit/4b53cc33a12a47e25d0d26446ee1ee96983e1b55#diff-cfe5d7af1aace846a15e33d66d919adf0094f53665bc14c3ff6530b85c425cb3)

You might have old parts of that code - `BLE_DEVICE_ID` uppercase should no longer be present as the lower case version `ble_device_id` is meant to be a variable while upper case was defined with a macro (I should have changed name indeed).

I have tried compiling the code on Arduino IDE (README.md updated) and I am not seeing the error

As long as you have it as a variable as in 
```
char BLE_DEVICE_ID[12]; // was char ble_device_id[12];
```
you are fine

**Comment by dookie454** [comment]
You are right, a fresh download with no other changes, compiles fine.  

Also, changing my version back to lower case works fine as well.    Maybe I had a reference to the upper case from my copied over TFT code.     Thanks again!!

**Comment by dookie454** [comment]
My error, thanks!  All set.
